### PR TITLE
Fixed multi-line copying and pasting bug & Fixed C #endif syntax highlight & Added #ifdef directive

### PR DESCRIPTION
**Pull request by polgartom**
This issue listed in the TODO.md file.
https://discord.com/channels/661732390355337246/1100701456950099978/1103153377237540874

### CODE REVIEW

**Comment by polgartom** [comment]
I hate this github stuff. Just copy my changes manually if you want to use it, just only few line of code

**Comment by focus-editor** [comment]
https://github.com/focus-editor/focus/commit/bb19fc1480f8397bb0ad8e424e552946f98c0b7b - slightly changed to make sure the last cursor doesn't get a trailing newline

https://github.com/focus-editor/focus/commit/b2f0b359f0184fa08192bd361e3cd8c2153829bc#diff-9c3cf967631ecc2f7398fd3e765e7f857b6fcc2453de84e28dcb49a39e17f69bR668

I didn't understand the other change you made, so I didn't include it

**Comment by polgartom** [comment]
I didn't understand either. The change what I made was I added two missing directives to C syntax highlighting #ifdef and #ifndef. Also I changed a little bit the directive highlighting mechanism, because if let's say you have a c header file probably the last token in that file is the #endif directive. Now, it won't highlight, because you have to add whitespace next to the directive. (as you will see in the images) I'll create an another commit then.

image
image

**Comment by focus-editor** [comment]
It's a general bug of the highlighter - any last token won't be recognised unless you add a newline or a space. I know about it, just never got around to fixing it yet

**Pull request closed without merging**
