### PR TITLE
Initial JS highlighting

### PR DESCRIPTION
**Pull request by simonvallz**
Add initial support for JS highlighting.

I don't have access to the compiler so I have a hard time testing it but I think this might be a good starting point.

### CODE REVIEW

**Comment by focus-editor** [comment]
Thanks. Impressive you're doing this without compiler access.
We'll try not to take too long to review it despite being busy.

**Comment by IRooc** [comment]
Could this highlighting also work for `.ts` files? I know typescript has extra stuff like generics, but at least it is something

**Comment by simonvallz** [comment]
I don't think it will be perfect with TypeScript (its probably not perfect for JavaScript either) but it will probably be better than no highlighting at all.

**Comment by focus-editor** [comment]
@simonvallz thanks again for your work. I've fixed the errors and made the code a bit simpler. Here's a patch file, please apply it to your code and I will accept the PR.
[js-changes.patch](https://github.com/focus-editor/focus/files/14796237/js-changes.patch)

**Comment by focus-editor** [comment]
Actually I just realised I can push the changes myself

**Pull request merged**
