### PR TITLE
Linux: Non-recursively watch parent directories of files outside of project directories

### PR DESCRIPTION
**Pull request by ileonte**
Not sure how correct this is, but I think it should work.
Should fix https://github.com/focus-editor/focus/issues/14

### CODE REVIEW

**Comment by focus-editor** [comment]
I can't test whether it works. Looks good to me, please merge if you've tested it and are happy with the change. The only thing is - not sure why we need an extra function. Wouldn't it make more sense to just pass `recursive` to the original `add_directories` call?

**Comment by ileonte** [comment]
> I can't test whether it works. Looks good to me, please merge if you've tested it and are happy with the change.

I've only tested on Linux, but I believe the other platform code paths should be the same. It would be good if you could confirm it at least doesn't break the Windows build (which again, it shouldn't, but just to be safe).

> The only thing is - not sure why we need an extra function. Wouldn't it make more sense to just pass `recursive` to the original `add_directories` call?

I initially had a `recursive` parameter added to `add_directories` but I decided to add a new function because of the following: on Windows and MacOS it doesn't look like you can do non-recursive directory watches; on Linux `INOTIFY` **only** does non-recursive, so the `File_Watcher` module tries to emulate the behavior of the other platforms by walking the base directory and adding each individual sub-directory to the watcher; because the `recursive` parameter would basically be a lie on every platform except Linux I decided that a new function may be better. I have no problem changing it back to the parameter version if you think that's better.

**Comment by focus-editor** [comment]
I will test on Windows tomorrow. 

It's still a bit confusing to me why `add_directories` and `add_single_directory` should have different interfaces even with the explanation you provided - it looks like the same function, just with a different number of directories.
What would be the problem if we added it to `add_directories`? I think it would be less confusing in the future.

**Comment by ileonte** [comment]
I guess the logic is that `add_directories` is a 'known' interface which implies recursive watches always. Adding a parameter that 66% of the time does nothing seems wrong. With a new function we "know" from the start that it lies to us most of the time.

**Comment by focus-editor** [comment]
That applies to the new function too

**Comment by focus-editor** [comment]
OK I'll leave the decision to you!

**Comment by ileonte** [comment]
Yes, that's what I said:
> With a new function we "know" from the start that it lies to us most of the time.

**Comment by focus-editor** [comment]
We don't know that because there's no comment explaining the decision

**Comment by ileonte** [comment]
Well, we "know" because we're talking about it here :))
Anyway, once you have the chance to test on Windows I'll pull this in, either with a comment explaining the new function or with the "recursive" parameter added, I'll sleep on it.

**Comment by focus-editor** [comment]
Just checked it on Windows - looks like it breaks the auto-reload when an individual file is open via the command line at startup.

Still works when the file is open using Ctrl-O

**Comment by ileonte** [comment]
> Just checked it on Windows - looks like it breaks the auto-reload when an individual file is open via the command line at startup.
> 
> Still works when the file is open using Ctrl-O

I just booted in Windows and tested, it seems to work fine for me. The way I tested is as follows:
* have the following paths in `[workspace dirs]` in the global config: `D:/dev/focus`, `D:/dev/langs/jai/modules`
* create `e:/test/brrap.txt` (outside of the workspace dirs)
* run `focus e:/test/brrap.txt`
* open `e:/test/brrap.txt` in notepad, make changes and save - Focus auto-reloads the file just fine
* in Focus open a workspace file from the Ctrl-P menu (for example `src/main.jai`). Open the same file in Notepad, make changes and save - Focus also auto-reloads this fine.

**Comment by focus-editor** [comment]
Apparently the bug only happens when the file you open is in the disk root - here's a screencast. If you open a dir not in the root it works
reload

**Comment by ileonte** [comment]
I'm not sure what to tell you, this works fine for me. Here is how that looks on my machine: https://www.youtube.com/watch?v=i5uTW0XVp9M
Note that for me both my branch and the official `0.2.0` binary from Github sometimes need to have some event trigger (like a mouse move/hover) to trigger the refresh, you can see it happening for both in my video. Other than that, they both work the same for me.

**Comment by focus-editor** [comment]
Maybe it's different on Windows 11. I'll check it one more time tomorrow. If it still fails, we'll merge it anyway since the benefits outweigh the bug

**Comment by ileonte** [comment]
Regardless of Windows differences, both `add_directories()` (https://github.com/ileonte/focus/blob/linux-support/modules/File_Watcher/module.jai#L111) and `add_single_directory()` (https://github.com/ileonte/focus/blob/linux-support/modules/File_Watcher/module.jai#L127) do the same thing on Windows, I really see no reason for there to be any difference.

Is `W:` on your machine a network mount or a local drive? Do you see the same issue with `C:`? (in my example `E:` is a local disk).

**Comment by focus-editor** [comment]
In your video you reopen the file using the open file dialog - I just did the same and can confirm it starts working after that, but not before. Try it fresh without reopening - I'm not lying, it doesn't refresh in your branch but does refresh in main.
Tested multiple times.

I think it's best to fix that now and not later when we forget the details - because eventually people are going to hit this bug and will be angry and will demand immediate fixes :)

**Comment by ileonte** [comment]
Again, not sure what to tell you, that works fine for me still: https://www.youtube.com/watch?v=_tB6s9vxddM

The only "issue" I see with the autoreload on my system is that sometimes I have to hover the window to trigger it, but that happens with my local build as well as the `0.2.0` binary from GitHub. This also happens on Linux, I suppose it's a byproduct of the way we wrote the event loop (`File_Watcher` does nothing that would wake `platform_wait_message()`).

As I said in my previous message, the code path for Windows has not changed in this PR as both `add_directories()` and `add_single_directory()` do the same thing in this case:

- https://github.com/ileonte/focus/blob/linux-support/modules/File_Watcher/module.jai#L112
- https://github.com/ileonte/focus/blob/linux-support/modules/File_Watcher/module.jai#L127

The main change this PR introduces is replacing a couple `add_directories()` calls with `add_single_directory()` (https://github.com/focus-editor/focus/pull/176/commits/56db907af979cd267be8e8ef35af8128497a88b4#diff-e78e8beb03cc61529ead3f4fb4746a34f76bfedfa9e099ce4f83e14b1a0a9074), but as far as I can tell these are equivalent on Windows (as shown above).

At this point I'm not sure what I'm supposed to fix (or even how to debug this).

**Comment by focus-editor** [comment]
It's going to remain a mystery then

**Pull request merged**
