### PR TITLE
When searching buffers also fuzzy match the whole file path.

### PR DESCRIPTION
**Pull request by Mulej**
Allows you to filter buffers both by path and by filename at the same time. Useful for opening module.jai files for example :)

### CODE REVIEW

**Comment by focus-editor** [comment]
I've tried this branch but can't see what exactly has changed. We're already searching by the path portion. Please can you give an example of a filter string that works with this change but doesn't without?

Also please note that the filter logic will have to be changed slightly soon, because currently we don't prioritise full matches while we really should

**Comment by Mulej** [comment]
An example would be "Input/module.jai", here I'm specifying both the path and the filename which doesn't work without this change.

> Also please note that the filter logic will have to be changed slightly soon, because currently we don't prioritise full matches while we really should

If the only thing changing is the fuzzy_match internals, then this will still work after the changes. Otherwise it might be a better idea to always match against the full file path (with filename included) and prioritize matches that match the leftmost parts of the path.

**Comment by valignatev** [comment]
I also want this. I can't, for example, ctrp+p for `focus/input.jai` or `focus input.jai` to distinguish from builtin jai modules easily

**Comment by focus-editor** [comment]
Thanks, I see what you mean now.

The reason I'm not merging your PR yet is because I need to take a careful look at the code which does the filtering and maybe redesign it a bit. If after that the design doesn't change then I'll merge your PR. Otherwise I will incorporate it into those changes so that it works.

The original idea was to make it behave more like VSCode and support queries separated by space, so that "jai/modules/Input/module.jai" could be matched by "mod inpu", for example. I just didn't have the time to implement it.

**Comment by focus-editor** [comment]
This has finally had some attention. It should now be possible to search by things separated by space or slash and they will be matched separately against both the name and the path. 

@Mulej if you're still using the editor, I will appreciate feedback on the new fuzzy match logic.

**Pull request closed without merging**
